[GLOBAL]
pants_version = "2.2.0"
backend_packages = ["pants.backend.python"]

[source]
root_patterns = ["/"]

[python-setup]
interpreter_constraints = [">=3.7"]
#requirement_constraints = "constraints.txt"
interpreter_search_paths = ["<PYENV>"]